# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'erfolge.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ErfolgeWindow(object):
    def setupUi(self, ErfolgeWindow):
        ErfolgeWindow.setObjectName("ErfolgeWindow")
        ErfolgeWindow.resize(1920, 1100)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:/Workspace/Bremen/logo.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        ErfolgeWindow.setWindowIcon(icon)
        ErfolgeWindow.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 green, stop:1 white);")

        self.centralwidget = QtWidgets.QWidget(ErfolgeWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.statusbar = QtWidgets.QStatusBar(ErfolgeWindow)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.setStyleSheet("background-color: green; color: black; font-size: 25px;")
        self.statusbar.setFixedHeight(50)  # Festlegen der Höhe der Statusleiste
        ErfolgeWindow.setStatusBar(self.statusbar)

        self.erfolgeTbl = QtWidgets.QTableWidget(self.centralwidget)
        self.erfolgeTbl.setGeometry(QtCore.QRect(1360, 90, 500, 521))
        self.erfolgeTbl.setStyleSheet("background-color:white;\n"
"font: 14pt \"Segoe UI\";\n")
        self.erfolgeTbl.setObjectName("erfolgeTbl")
        self.erfolgeTbl.setColumnCount(3)
        self.erfolgeTbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.erfolgeTbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.erfolgeTbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.erfolgeTbl.setHorizontalHeaderItem(2, item)
        self.erfolgeTbl.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)


        self.dfb = QtWidgets.QLabel(self.centralwidget)
        self.dfb.setGeometry(QtCore.QRect(400, 150, 171, 331))
        self.dfb.setText("")
        self.dfb.setPixmap(QtGui.QPixmap("F:/Workspace/Bremen/dfb.jpg"))
        self.dfb.setObjectName("dfb")


        self.ligapokal = QtWidgets.QLabel(self.centralwidget)
        self.ligapokal.setGeometry(QtCore.QRect(950, 370, 341, 271))
        self.ligapokal.setText("")
        self.ligapokal.setPixmap(QtGui.QPixmap("F:/Workspace/Bremen/ligapokal.jpg"))
        self.ligapokal.setObjectName("ligapokal.jpg")


        self.pokal = QtWidgets.QLabel(self.centralwidget)
        self.pokal.setGeometry(QtCore.QRect(20, 410, 191, 321))
        self.pokal.setText("")
        self.pokal.setPixmap(QtGui.QPixmap("F:/Workspace/Bremen/europapokal.jpg"))
        self.pokal.setObjectName("pokal")


        self.meister = QtWidgets.QLabel(self.centralwidget)
        self.meister.setGeometry(QtCore.QRect(950, 150, 311, 191))
        self.meister.setText("")
        self.meister.setPixmap(QtGui.QPixmap("F:/Workspace/Bremen/meister.jpg"))
        self.meister.setObjectName("meister")


        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(1690, 615, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("background-color:red;\n"
"font: 14pt \"Segoe UI\";\n"
"border-radius: 20px;")
        self.saveBtn.setObjectName("saveBtn")


        self.uefa = QtWidgets.QLabel(self.centralwidget)
        self.uefa.setGeometry(QtCore.QRect(620, 420, 211, 431))
        self.uefa.setText("")
        self.uefa.setPixmap(QtGui.QPixmap("F:/Workspace/Bremen/euroleague.jpg"))
        self.uefa.setObjectName("uefa")


        self.champions = QtWidgets.QLabel(self.centralwidget)
        self.champions.setGeometry(QtCore.QRect(1350, 690, 231, 231))
        self.champions.setText("")
        self.champions.setPixmap(QtGui.QPixmap("F:/Workspace/Bremen/ChampionsLeague.jpg"))
        self.champions.setObjectName("champions")
        ErfolgeWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(ErfolgeWindow)
        QtCore.QMetaObject.connectSlotsByName(ErfolgeWindow)

    def retranslateUi(self, ErfolgeWindow):
        _translate = QtCore.QCoreApplication.translate
        ErfolgeWindow.setWindowTitle(_translate("ErfolgeWindow", "SV Werder Bremen"))
        item = self.erfolgeTbl.horizontalHeaderItem(0)
        item.setText(_translate("ErfolgeWindow", "ID"))
        item = self.erfolgeTbl.horizontalHeaderItem(1)
        item.setText(_translate("ErfolgeWindow", "Titel"))
        item = self.erfolgeTbl.horizontalHeaderItem(2)
        item.setText(_translate("ErfolgeWindow", "Jahr"))
        self.saveBtn.setText(_translate("ErfolgeWindow", "Speichern"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErfolgeWindow = QtWidgets.QMainWindow()
    ui = Ui_ErfolgeWindow()
    ui.setupUi(ErfolgeWindow)
    ErfolgeWindow.show()
    sys.exit(app.exec_())
