# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saison.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaisonWindow(object):
    def setupUi(self, SaisonWindow):
        SaisonWindow.setObjectName("SaisonWindow")
        SaisonWindow.resize(1920, 1100)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:/Workspace/Bremen/logo.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        SaisonWindow.setWindowIcon(icon)
        SaisonWindow.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 green, stop:1 white);")
        self.centralwidget = QtWidgets.QWidget(SaisonWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.statusbar = QtWidgets.QStatusBar(SaisonWindow)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.setStyleSheet("background-color: green; color: black; font-size: 25px;")
        self.statusbar.setFixedHeight(50)  # Festlegen der Höhe der Statusleiste
        SaisonWindow.setStatusBar(self.statusbar)


        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(1520, 900, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("background-color:red;\n"
                                   "font: 14pt \"Segoe UI\";\n"
                                   "border-radius: 20px;")
        self.saveBtn.setObjectName("saveBtn")


        self.saisontbl = QtWidgets.QTableWidget(self.centralwidget)
        self.saisontbl.setGeometry(QtCore.QRect(150, 90, 1550, 800))
        self.saisontbl.setStyleSheet("font: 12pt \"Segoe UI\";background-color:white;border: 1px solid black;")
        self.saisontbl.setShowGrid(True)
        self.saisontbl.setGridStyle(QtCore.Qt.SolidLine)
        self.saisontbl.setObjectName("saisontbl")
        self.saisontbl.setColumnCount(10)
        self.saisontbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.saisontbl.setHorizontalHeaderItem(9, item)
        SaisonWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SaisonWindow)
        QtCore.QMetaObject.connectSlotsByName(SaisonWindow)

    def retranslateUi(self, SaisonWindow):
        _translate = QtCore.QCoreApplication.translate
        SaisonWindow.setWindowTitle(_translate("SaisonWindow", "SV Werder Bremen"))
        self.saveBtn.setText(_translate("SaisonWindow", "Speichern"))
        self.saisontbl.setSortingEnabled(False)
        item = self.saisontbl.horizontalHeaderItem(0)
        item.setText(_translate("SaisonWindow", "ID"))
        item = self.saisontbl.horizontalHeaderItem(1)
        item.setText(_translate("SaisonWindow", "Saison"))
        item = self.saisontbl.horizontalHeaderItem(2)
        item.setText(_translate("SaisonWindow", "Platz"))
        item = self.saisontbl.horizontalHeaderItem(3)
        item.setText(_translate("SaisonWindow", "Siege"))
        item = self.saisontbl.horizontalHeaderItem(4)
        item.setText(_translate("SaisonWindow", "Unentschieden"))
        item = self.saisontbl.horizontalHeaderItem(5)
        item.setText(_translate("SaisonWindow", "Niederlagen"))
        item = self.saisontbl.horizontalHeaderItem(6)
        item.setText(_translate("SaisonWindow", "Tore"))
        item = self.saisontbl.horizontalHeaderItem(7)
        item.setText(_translate("SaisonWindow", "Tordifferenz"))
        item = self.saisontbl.horizontalHeaderItem(8)
        item.setText(_translate("SaisonWindow", "Punkte"))
        item = self.saisontbl.horizontalHeaderItem(9)
        item.setText(_translate("SaisonWindow", "Liga"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaisonWindow = QtWidgets.QMainWindow()
    ui = Ui_SaisonWindow()
    ui.setupUi(SaisonWindow)
    SaisonWindow.show()
    sys.exit(app.exec_())
