# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spieler.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpielerWindow(object):
    def setupUi(self, SpielerWindow):
        SpielerWindow.setObjectName("SpielerWindow")
        SpielerWindow.resize(1920, 1100)
        icon = QtGui.QIcon("F:/Workspace/Bremen/logo.bmp")
        SpielerWindow.setWindowIcon(icon)
        SpielerWindow.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 green, stop:1 white);")

        self.centralwidget = QtWidgets.QWidget(SpielerWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.spielerTbl = QtWidgets.QTableWidget(self.centralwidget)
        self.spielerTbl.setGeometry(QtCore.QRect(200, 70, 1400, 711))
        self.spielerTbl.setStyleSheet("font: 12pt \"Segoe UI\";background-color:white;border: 1px solid black;")
        self.spielerTbl.setObjectName("spielerTbl")
        self.spielerTbl.setColumnCount(9)
        self.spielerTbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.spielerTbl.setHorizontalHeaderItem(8, item)


        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(1440, 800, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("background-color:red;\n"
                                   "font: 14pt \"Segoe UI\";\n"
                                   "border-radius: 20px;")
        self.saveBtn.setObjectName("saveBtn")


        SpielerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SpielerWindow)
        self.statusbar.setObjectName("statusbar")
        SpielerWindow.setStatusBar(self.statusbar)


        self.retranslateUi(SpielerWindow)
        QtCore.QMetaObject.connectSlotsByName(SpielerWindow)

    def retranslateUi(self, SpielerWindow):
        _translate = QtCore.QCoreApplication.translate
        SpielerWindow.setWindowTitle(_translate("SpielerWindow", "SpielerWindow"))
        item = self.spielerTbl.horizontalHeaderItem(0)
        item.setText(_translate("SpielerWindow", "ID"))
        item = self.spielerTbl.horizontalHeaderItem(1)
        item.setText(_translate("SpielerWindow", "Vorname"))
        item = self.spielerTbl.horizontalHeaderItem(2)
        item.setText(_translate("SpielerWindow", "Nachname"))
        item = self.spielerTbl.horizontalHeaderItem(3)
        item.setText(_translate("SpielerWindow", "Nationalität"))
        item = self.spielerTbl.horizontalHeaderItem(4)
        item.setText(_translate("SpielerWindow", "Von"))
        item = self.spielerTbl.horizontalHeaderItem(5)
        item.setText(_translate("SpielerWindow", "Bis"))
        item = self.spielerTbl.horizontalHeaderItem(6)
        item.setText(_translate("SpielerWindow", "Ligaspiele"))
        item = self.spielerTbl.horizontalHeaderItem(7)
        item.setText(_translate("SpielerWindow", "Ligatore"))
        item = self.spielerTbl.horizontalHeaderItem(8)
        item.setText(_translate("SpielerWindow", "Position"))
        self.saveBtn.setText(_translate("SpielerWindow", "Speichern"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpielerWindow = QtWidgets.QMainWindow()
    ui = Ui_SpielerWindow()
    ui.setupUi(SpielerWindow)
    SpielerWindow.show()
    sys.exit(app.exec_())
